import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {FileBlob,PresentationFile} from '@oai/artifact-tool';
import {finalizePresentation,applyPresentationChartFont} from '/Users/dhwanilchauhan/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/dhwanilchauhan/Desktop/RCA Try 1',build=root+'/.rca-progress-build',skill='/Users/dhwanilchauhan/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations',source='/Users/dhwanilchauhan/Downloads/S&T_PTC_July2026Presentation.pptx';
const p=await PresentationFile.importPptx(await FileBlob.load(source));for(const s of [...p.slides.items])s.delete();
const C={gold:'#DDAB18',teal:'#8CADAE',blue:'#5D9BB4',red:'#D16349',olive:'#B7A400',ink:'#222222'};
function txt(s,t,x,y,w,h,size=27,color=C.ink,bold=false,align='left'){let q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=t;q.text.style={typeface:'Arial',fontSize:size,color,bold,alignment:align,autoFit:'none'};return q;}
function slide(title,notes,cover=false){let s=p.slides.add({layoutId:cover?'/ppt/slideLayouts/slideLayout3.xml':'/ppt/slideLayouts/slideLayout2.xml'});s.shapes.deleteAll();if(!cover)txt(s,title,97,18,963,80,42.6667,C.gold,true);s.speakerNotes.textFrame.setText(notes);return s;}
function node(s,title,sub,x,y,w=205,h=124,color=C.blue){if(sub)h=Math.max(h,154);let q=s.shapes.add({geometry:'roundRect',position:{left:x,top:y,width:w,height:h},fill:'#FFFFFF',line:{fill:color,width:2},borderRadius:8});txt(s,title,x+12,y+12,w-24,54,24,C.ink,true,'center');if(sub)txt(s,sub,x+12,y+76,w-24,h-80,20,'#555555',false,'center');return q;}
function link(s,a,b,from='right',to='left',color='#A8ADAD'){return s.shapes.connect(a,b,{kind:'elbow',fromSide:from,toSide:to,line:{fill:color,width:2},tail:{type:'arrow',width:'med',length:'med'}});}
async function img(s,name,x,y,w,h){s.images.add({blob:await fs.readFile(build+'/'+name),contentType:'image/png',alt:name.replace('.png',''),fit:'contain',position:{left:x,top:y,width:w,height:h}});}
const notes={baseline:source+' slides 7–13.',current:root+'/Try 7/TRY7_EXECUTIVE_PLAN.md, section 10 implementation receipt and observed smoke outcome.',flow:root+'/RCA_RESEARCH_OVERVIEW_AND_PLAN.md sections 5, 8; '+root+'/Try 7/TRY7_EXECUTIVE_PLAN.md sections 4, 10.',compare:root+'/Try 6/evals/v1-v2-presentation-review/output/Try6_V1_V2_Evidence_Review.md sections 1–3; '+root+'/Try 6/public/history/featured-causal-boards.json.',packages:root+'/Synthetic Evidence Packages 2026-09-22/README_OPERATOR_ONLY.md.',plan:root+'/RCA_IMPLEMENTATION_AND_PAPER_CHECKLIST.md sections C–E.'};
let s=slide('',notes.baseline+' Progress cutoff 22 September 2026, not a confirmed meeting date.',true);
txt(s,'Project #19\nStandalone Root Cause Analysis\nProgress Since July 2026',160,175,960,240,54,C.gold,true,'center');txt(s,'Progress through 22 September 2026',325,535,670,50,26);
s=slide('Progress Since July',notes.baseline+' '+notes.current+' Screenshot: current Try 7 local interface captured 22 September 2026. Workflow availability is not evidence of RCA accuracy.');
txt(s,'Current investigation workspace',490,112,730,42,29,C.ink,true);await img(s,'current-app.png',460,164,770,434);
txt(s,'JULY',48,120,370,40,26,C.gold,true);txt(s,'Stepwise RCA concept\nInitial causal mapping\nQwen testing planned',48,169,385,139,28);
txt(s,'SINCE JULY',48,347,375,40,26,C.gold,true);txt(s,'Preserved investigations\nEvidence-driven revisions\nRecorded Qwen experiments',48,397,385,140,28);
txt(s,'Prototype implemented. Causal quality remains under evaluation.',65,626,1110,42,27,C.ink,true);
s=slide('How the Investigation Now Works',notes.flow+' Simplified conceptual workflow. The diagram summarizes responsibilities, not separate fixed sequential API agents. Review outcomes and questions can reopen investigation work.');
txt(s,'One incident develops through evidence and successive saved versions',61,113,1145,46,28,'#555555');
let a=node(s,'Incident + records','Original sources retained',55,203,230,138,C.teal),b=node(s,'Initial understanding','Entities and hypotheses',365,203,230,138,C.blue),c=node(s,'Targeted expertise','Focused questions',675,203,230,138,C.blue);link(s,a,b);link(s,b,c);
let d=node(s,'Questions + answers','Requests and sourced answers',675,419,230,144,C.olive),e=node(s,'Review + revision','Facts, roles and links',365,419,230,144,C.red),f=node(s,'Saved versions','Board and open questions',55,419,230,144,C.teal);link(s,c,d,'bottom','top');link(s,d,e,'left','right');link(s,e,f,'left','right');
txt(s,'NEW\nEVIDENCE',973,286,228,84,28,C.gold,true,'center');let newEv=node(s,'Later records','Answers or corrections',964,412,236,144,C.olive);link(s,newEv,d,'left','right',C.olive);txt(s,'New information can strengthen, challenge or withdraw an explanation.',64,619,1100,45,27,C.ink,true);
s=slide('What Changed Between V1 and V2',notes.compare+' One Try 6 development case, IA-16036, Qwen3.5. Counts include focal event. V1 5 nodes/4 active links/0 verified links; V2 9/6/0. No claim that greater size means greater accuracy. Diagram at right is an abbreviated excerpt of the two opposing preceded links present in saved V1, not a correct process model.');
txt(s,'Instrument-air case: saved partial investigations',55,113,1150,44,28,'#555555');
let chart=s.charts.add('bar',{position:{left:50,top:207,width:663,height:342},categories:['Board nodes','Active links','Verified links'],series:[{name:'V1',values:[5,4,0],fill:C.teal},{name:'V2',values:[9,6,0],fill:C.gold}],barOptions:{direction:'column',grouping:'clustered'},hasLegend:true,legend:{position:'bottom',textStyle:{fontSize:20}},xAxis:{textStyle:{fontSize:19}},yAxis:{textStyle:{fontSize:18}},dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:22,bold:true}}});applyPresentationChartFont(chart,{fontFamily:'Arial'});
txt(s,'A concrete issue found',766,178,438,45,27,C.ink,true);let loss=node(s,'Pressure loss','',787,263,183,94,C.red),rec=node(s,'Recovery','',1032,263,183,94,C.teal);link(s,loss,rec);link(s,rec,loss,'bottom','bottom',C.red);txt(s,'V1 retained both directions\nfor the “preceded” relationship.',760,393,446,91,25);txt(s,'The board grew.\nKey causal errors remained.',760,504,443,100,25,C.red,true);
txt(s,'5 to 9 nodes. Verified connections stayed at 0.',62,621,1110,44,30,C.ink,true);
s=slide('Improvements to Evidence Review',notes.current+' These functions are described in the implementation receipt; full-plan acceptance is incomplete. The 97 checks are recorded deterministic software checks, not model accuracy scores.');
txt(s,'Corrections now have an explicit route back to the investigation',57,112,1150,46,28,'#555555');
a=node(s,'Source evidence','Preserved originals',56,210,235,135,C.teal);b=node(s,'Proposed correction','Source-bound change',355,210,235,135,C.blue);c=node(s,'Re-review','Check the revised claim',654,210,235,135,C.red);d=node(s,'Saved revision','History + current view',953,210,235,135,C.olive);link(s,a,b);link(s,b,c);link(s,c,d);
txt(s,'Three separate judgments',57,401,1110,42,28,C.ink,true);
a=node(s,'Factual support','Does the source establish it?',57,464,350,124,C.teal);b=node(s,'Causal role','Is it an event, condition or barrier?',447,464,350,124,C.blue);c=node(s,'Connection validity','Is the proposed relationship justified?',837,464,350,124,C.red);
txt(s,'97 recorded software checks passed. Model RCA improvement still needs testing.',57,627,1120,42,26,C.ink,true);
s=slide('Latest Qwen Investigation',notes.current+' Screenshot of the saved unscored Try 7 pneumatic-carriage smoke run. The screenshot shows the current app displaying the historical V1 snapshot. 21 tasks completed; partial version; 5 observations plus focal event, zero causal links; execution-inconclusive. Post-run fixes are not validated by a fresh frozen-config experiment.');
await img(s,'current-board.png',43,151,854,479);
txt(s,'21',935,162,270,74,62,C.gold,true);txt(s,'tasks completed',935,238,285,47,27);txt(s,'Partial V1',935,325,287,50,34,C.ink,true);txt(s,'5 observations\n+ focal event\n0 causal links',935,392,275,142,28);
txt(s,'Real run, preserved output. Execution remains inconclusive.',56,640,1115,40,27,C.red,true);
s=slide('Staged Evidence for Validation',notes.packages+' Two historically anchored synthetic reconstructions, not recovered company records. Both are derivatives of previously used development cases, not independent held-out cases. B0/B1/B2 are cumulative releases corresponding to V1/V2/V3. No new RCA run is claimed.');
txt(s,'Two development cases',55,118,1100,43,28,C.ink,true);txt(s,'R3 beam fall',65,184,477,40,31,C.blue,true);txt(s,'Technical review required',65,231,475,40,25);txt(s,'Instrument-air loss',668,184,500,40,31,C.blue,true);txt(s,'Prepared for pilot',668,231,493,40,25);
a=node(s,'B0: starter evidence','Initial account and available records',60,348,322,157,C.teal);b=node(s,'B1: new evidence','Records that distinguish explanations',475,348,322,157,C.blue);c=node(s,'B2: further evidence','Deeper context or a correction',890,348,322,157,C.red);link(s,a,b);link(s,b,c);
txt(s,'V1',162,526,110,50,34,C.teal,true,'center');txt(s,'V2',579,526,110,50,34,C.blue,true,'center');txt(s,'V3',992,526,110,50,34,C.red,true,'center');txt(s,'Synthetic reconstructions. Independent technical validation remains pending.',55,629,1135,43,25,C.ink,true);
s=slide('Next Steps',notes.plan+' '+notes.current+' Proposed milestones, not completed outcomes or dated commitments. Review R3 mechanics before scored use. Use equivalent evidence for baseline comparisons.');
txt(s,'Next milestone: one reproducible investigation across three evidence releases',55,115,1150,54,28,'#555555');
a=node(s,'Freeze the pilot','Model, prompts and release schedule',58,259,244,163,C.teal);b=node(s,'Run V1–V3','Save every input, board and revision',360,259,244,163,C.blue);c=node(s,'Baseline comparison','Same model and same evidence',662,259,244,163,C.olive);d=node(s,'Assess quality','Evidence, mechanisms and revisions',964,259,244,163,C.red);link(s,a,b);link(s,b,c);link(s,c,d);
txt(s,'Technical review',66,505,480,48,31,C.ink,true);txt(s,'Review case realism and\ncausal interpretation.',66,563,480,85,27);txt(s,'Success criterion',668,505,510,48,31,C.ink,true);txt(s,'Evidence produces justified\nchanges in the explanation.',668,563,510,85,27);
const candidate=build+'/visual-candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){let b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(build+`/visual-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:root+'/RCA Presentation Outputs/September Progress/RCA_Progress_Visual_July_Theme_v2.pptx',pythonExecutable:'/Users/dhwanilchauhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],fontPolicy:{basis:'reference',families:['Arial','Calibri'],referencePath:source,referenceSha256:crypto.createHash('sha256').update(await fs.readFile(source)).digest('hex')},requiredNativeChartOwnerSlides:[4],materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:build+'/visual-validation-v2.json'});console.log('Visual presentation exported');
