export const roles = [
  { id: "focal_point", section: "2.1", name: "Focal Point Identifier", kind: "model", description: "Identifies the central event or condition the investigation must explain." },
  { id: "board", section: "2.2", name: "Question Queue + Board State", kind: "code", description: "Owns nodes, branch depth, links, statuses, precedence rules, and versions." },
  { id: "list_a", section: "3A.1", name: "List A", kind: "model", description: "Creates the named inventory of things explicitly in the incident." },
  { id: "list_b", section: "3A.2", name: "List B", kind: "model", description: "Adds relevant inferred things, clearly distinct from report-extracted things." },
  { id: "keep_digging", section: "5.1.1", name: "Keep Digging", kind: "model", description: "Names specific next causes to investigate and their available facts." },
  { id: "stop_here", section: "5.1.2", name: "Stop Here", kind: "model", description: "Independently applies predefined stopping criteria to the current branch." },
  { id: "node_referee", section: "5.1.3", name: "Node Referee", kind: "code", description: "Applies precedence: person action keeps digging; otherwise parks when evidence is inconclusive." },
  { id: "controllability", section: "5.2", name: "Controllability", kind: "model", description: "Names who in the plant could change the condition and exactly what could change." },
  { id: "control_gap", section: "5.2", name: "Control Gap", kind: "model", description: "When direct control is absent, identifies the safeguard that should have protected the system." },
  { id: "cause_proposer", section: "5.5.1", name: "Cause Proposer", kind: "model", description: "Proposes conditions that had to be present together for the node." },
  { id: "necessity", section: "5.5.2", name: "Necessity Checker", kind: "model", description: "Tests each proposed cause by removing it." },
  { id: "sufficiency", section: "5.5.3", name: "Sufficiency Checker", kind: "model", description: "Tests whether the proposed set is enough or missing a cause." },
  { id: "why_referee", section: "5.5.4", name: "Why Referee", kind: "code", description: "Drops unnecessary conditions, identifies gaps, and permits one re-ask." },
  { id: "type_area", section: "5.6", name: "Type + Area", kind: "model", description: "Classifies every new cause as an event or standing condition and assigns its RCA area." },
  { id: "fact_retriever", section: "5.7.1", name: "Fact Retriever", kind: "model", description: "Selects relevant fact-table rows by entity, fact type, and meaning." },
  { id: "support", section: "5.7.2", name: "Support", kind: "model", description: "Independently evaluates whether selected rows support the proposed cause." },
  { id: "denial", section: "5.7.3", name: "Denial", kind: "model", description: "Independently evaluates whether selected rows contradict the proposed cause." },
  { id: "verdict_referee", section: "5.7.4", name: "Verdict Referee", kind: "code", description: "Applies fact-ID validation and denial-over-support precedence." },
  { id: "root_test", section: "6.1", name: "Root Test", kind: "model", description: "Tests whether a specific preventive intervention can be written against a candidate root." },
  { id: "fix_writer", section: "6.2", name: "Fix Writer", kind: "model", description: "Writes a precise change, rejecting vague recommendations." },
  { id: "effectiveness", section: "6.3", name: "Corrective Action Effectiveness Validation", kind: "model", description: "Tests whether the proposed action would prevent or materially interrupt the chain." },
  { id: "prevent_check", section: "6.4", name: "Prevent / Materially Interrupt Check", kind: "code", description: "Confirms a root only when the effectiveness test succeeds." },
  { id: "integrity", section: "7", name: "Causal Graph Integrity", kind: "code", description: "Detects cycles, duplicate causes, unsupported jumps, orphans, and invalid statuses." },
] as const;
