import type { RunRow } from '@/src/engine/tasks/d1-store';
import type { EngineInput } from '@/src/engine/types';
import { readJSON,readState,putJSON,putState } from '@/src/engine/tasks/artifacts';
import { digest } from '@/src/engine/identity';
import { literalReviewShape,literalReviewContract } from '@/src/engine/review/literal-contract';
import { normalizeReviewFormatting,REVIEW_FORMATTING_POLICY } from '@/src/engine/review/formatting';
import { assessLiteralClaim } from '@/src/engine/review/literal-decision';
import { applyEvidenceTask } from '@/src/stages/evidence-reading/task';
import { project } from '@/src/engine/board/projection';

/** Operator-authorized, application-only repair at an idle paused checkpoint.
 * No new model call, altered evidence, rewritten trace, or published-version edit. */
export async function activateReviewFormatting(db:D1Database,runId:string,expectedGeneration:number,
  checkpointHash:string,reason:string,recoverTaskIds:string[]=[]) {
  const row=await db.prepare('SELECT * FROM engine_runs WHERE id=?').bind(runId).first<RunRow>();
  if(!row||row.status!=='paused'||row.generation!==expectedGeneration||row.lease_until>Date.now())
    throw Error('Formatting activation requires the exact idle, paused checkpoint.');
  if(await db.prepare('SELECT id FROM versions WHERE id=? OR (track_id=? AND number=?)').bind(runId,row.track_id,row.number).first())
    throw Error('Published versions are immutable.');
  if(checkpointHash!==await digest([row.input_json,row.state_json,row.snapshot_json])||!reason.trim())
    throw Error('Checkpoint hash/reason missing or changed.');
  const state=await readState(db,row.state_json),input=await readJSON<EngineInput>(db,row.input_json);
  if(!state||state.tasks.some(t=>t.status==='running'))throw Error('Wait for in-flight inference to finish before activation.');
  if(state.reviewFormattingPolicy)throw Error('Formatting policy already set; refusing an implicit policy replacement.');
  // The complete old checkpoint is retained in immutable, content-addressed storage.
  const backup=await putJSON(db,row),at=new Date().toISOString(),retiredQuestionIds:string[]=[];
  state.reviewFormattingPolicy=REVIEW_FORMATTING_POLICY;
  for(const taskId of new Set(recoverTaskIds)) {
    const task=state.tasks.find(t=>t.id===taskId),finding=state.findings.find(f=>task?.targetIds.includes(f.id));
    if(!task||task.kind!=='review'||task.status!=='failed'||!task.traceId||!finding||task.targetRevision!==finding.revision)
      throw Error('Only a failed review of an unchanged finding can be revalidated.');
    const call=await db.prepare('SELECT * FROM engine_calls WHERE id=? AND run_id=? AND task_id=?')
      .bind(task.traceId,runId,task.id).first<{status:string;request_json:string;result_json:string}>();
    if(!call||call.status!=='failed')throw Error('A finished original failed trace is required.');
    const request=await readJSON<{kind:string;packet:{target:{statement:string};evidence:Array<{ref:string;text:string}>};selectedEvidence:string[]}>(db,call.request_json);
    const result=await readJSON<{output?:{output?:unknown}}>(db,call.result_json);
    const raw=literalReviewShape.parse(result.output?.output);
    const formatted=normalizeReviewFormatting(raw,REVIEW_FORMATTING_POLICY);
    if(!formatted.normalization)throw Error('Selected response has no recognized empty marker; do not repair its verdict.');
    if(request.kind!=='review'||request.packet.target.statement!==finding.statement)throw Error('Original review target changed.');
    const spans=new Map(state.sources.flatMap(s=>s.spans).map(s=>[s.id,s]));
    const refs={sources:new Map<string,string>(),findings:new Map<string,string>(),questions:new Map<string,string>()};
    const lines:Record<string,number[]>={};
    if(request.packet.evidence.length!==request.selectedEvidence.length)throw Error('Original evidence mapping is incomplete.');
    request.packet.evidence.forEach((entry,i)=>{
      const id=request.selectedEvidence[i],span=spans.get(id);
      if(!span||span.modality||entry.ref!==`S${i+1}`||entry.text!==span.text.split('\n').map((line,n)=>`${n+1}|${line}`).join('\n'))
        throw Error('Original evidence changed or cannot be reproduced exactly.');
      refs.sources.set(entry.ref,id);lines[entry.ref]=span.text.split('\n').flatMap((line,n)=>line.trim()?[n+1]:[]);
    });
    literalReviewContract([...refs.sources.keys()],finding.statement,lines).parse(raw);
    assessLiteralClaim(state,finding,raw,refs); // Full consistency/provenance gates before changes.

    // Retire only literal placeholder questions generated by this failed review.
    // Preserve completed broker work and the old questions in the checkpoint;
    // never delete an answered question or one serving another live question.
    const placeholders=new Set(formatted.normalization.removed.map(p=>`What evidence, if any, can resolve this stated gap: “${p.trim()}”?`));
    const retired=state.questions.filter(q=>task.producedIds?.includes(q.id)&&placeholders.has(q.text));
    for(const q of retired) {
      if(q.answer||q.findingIds.length||q.answerSpanIds.length||q.coveredBy||q.reviewTargets?.some(id=>id!==finding.id)
        ||state.questions.some(other=>other.coveredBy===q.id)
        ||state.tasks.some(t=>t.targetIds.includes(q.id)&&(t.kind!=='broker'||t.status!=='completed')))
        throw Error('Placeholder question has downstream work; explicit dependency review is required.');
      retiredQuestionIds.push(q.id);
      state.changes.push({targetId:q.id,kind:'rejected',reason:'Retired formatting-only placeholder question; original question and broker trace retained in the activation backup. No incident fact was answered.'});
    }
    const oldError=task.error,previousQuestions=new Set(state.questions.map(q=>q.id));
    state.questions=state.questions.filter(q=>!retired.some(r=>r.id===q.id));
    const quarantined=state.quarantine.filter(q=>q.taskId===task.id);
    if(quarantined.some(q=>!q.item||typeof q.item!=='object'||Object.keys(q.item).some(k=>k!=='traceId')||(q.item as {traceId?:string}).traceId!==task.traceId))
      throw Error('Review has unrelated quarantined items; refusing blanket removal.');
    state.quarantine=state.quarantine.filter(q=>q.taskId!==task.id);
    applyEvidenceTask(state,task,raw,refs);
    task.status='completed';task.error='';task.output={decision:{summary:finding.reviewReason}};
    task.producedIds=[...(task.producedIds||[]).filter(id=>!retired.some(q=>q.id===id)),...state.questions.filter(q=>!previousQuestions.has(q.id)).map(q=>q.id)];
    task.formattingRecovery={policy:REVIEW_FORMATTING_POLICY,at,traceId:task.traceId,previousError:oldError};
    state.changes.push({targetId:task.id,kind:'rechecked',reason:'Saved reviewer output passed unchanged evidence/target/consistency checks after formatting-only normalization. Original failed trace retained; no new inference.'});
  }
  state.reviewFormattingMigrations=[...(state.reviewFormattingMigrations||[]),{policy:REVIEW_FORMATTING_POLICY,at,reason,checkpointHash,backup,
    recoveredTaskIds:[...new Set(recoverTaskIds)],retiredQuestionIds}];
  state.pauseReason='';
  state.changes.push({targetId:runId,kind:'revised',reason:`Operator-enabled ${REVIEW_FORMATTING_POLICY}: ${reason} Frozen input, completed work and original traces preserved.`});
  const changed=await db.prepare(`UPDATE engine_runs SET state_json=?,snapshot_json=?,status='queued',pause_reason='',
    lease=NULL,lease_until=0,generation=generation+1,updated_at=? WHERE id=? AND status='paused' AND generation=? AND lease_until=0`)
    .bind(await putState(db,state),await putJSON(db,project(state,input,'queued')),at,runId,expectedGeneration).run();
  if(!changed.meta.changes)throw Error('Checkpoint changed during activation; no dispatch was authorized.');
  return {runId,policy:REVIEW_FORMATTING_POLICY,version:row.number,recoveredTaskIds:recoverTaskIds,retiredQuestionIds,backup,queued:true};
}
